# Generated by Django 5.2 on 2025-05-05 11:37
# pylint: disable=missing-module-docstring,missing-class-docstring
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="user name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="user e-mail"),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="time when message was created at",
                    ),
                ),
            ],
        ),
    ]
