# Generated by Django 5.2.1 on 2025-05-12 09:08
# pylint: disable=missing-module-docstring,missing-class-docstring
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrocat", "0003_remove_user_hashed_password_user_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spaceobject",
            name="image_path",
        ),
        migrations.AlterField(
            model_name="spaceobject",
            name="ex",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spaceobject",
            name="g",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spaceobject",
            name="m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spaceobject",
            name="p",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spaceobject",
            name="period",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spaceobject",
            name="radius",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spaceobject",
            name="v",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
