# Generated by Django 5.2.1 on 2025-05-13 09:14
# pylint: disable=missing-module-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("astrocat", "0005_auto_20250512_1209"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="spaceobject",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="spacesystem",
            options={"ordering": ["id"]},
        ),
    ]
