name: astrocat

services:
  database:
    container_name: ${POSTGRES_CONTAINER_NAME:-astro_db}
    image: postgis/postgis:16-3.4
    restart: on-failure
    env_file:
      - ./db.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d postgres
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  fileserver:
    container_name: ${MINIO_CONTAINER_NAME:-fileserver}
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio_data:/data
    env_file:
      - ./minio.env
    healthcheck:
      test: mc ready local
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    command: server --console-address ":9001" /data

  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - ./.env
    depends_on:
      - database
      - fileserver
